### ISSUE TITLE
Funky output for available wireframes

### ISSUE THREAD

**Issue by krumware** [privateerproj/privateer#15]
I was able to specify my binaries path via:
the example wireframe is located in cli/bin properly.
```
loglevel: trace
WriteDirectory: test_output
binaries-path: ~/code/privateerproj/cli/bin
Raids:
  Wireframe:
    JokeName: Jimmy
```

when running `privateer list`, this was the output:

```
krumware@PF-3842ND:~/code/privateerproj/cli$ ./privateer.exe list -c ./config.yml
| Available  | Requested  |
| wireframe  | Not Found  
```
